//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан программой.
//     Исполняемая версия:4.0.30319.18010
//
//     Изменения в этом файле могут привести к неправильной работе и будут потеряны в случае
//     повторной генерации кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MyPress.Client.Resources {
    using System;
    
    
    /// <summary>
    ///   Класс ресурса со строгой типизацией для поиска локализованных строк и т.д.
    /// </summary>
    // Этот класс создан автоматически классом StronglyTypedResourceBuilder
    // с помощью такого средства, как ResGen или Visual Studio.
    // Чтобы добавить или удалить член, измените файл .ResX и снова запустите ResGen
    // с параметром /str или перестройте свой проект VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Возвращает кэшированный экземпляр ResourceManager, использованный этим классом.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MyPress.Client.Resources.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Перезаписывает свойство CurrentUICulture текущего потока для всех
        ///   обращений к ресурсу с помощью этого класса ресурса со строгой типизацией.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абайская РВЛ.
        /// </summary>
        public static string Abayskay {
            get {
                return ResourceManager.GetString("Abayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Абралинский ЗВЛ.
        /// </summary>
        public static string Abralynskay {
            get {
                return ResourceManager.GetString("Abralynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Агадырская  ЗВЛ.
        /// </summary>
        public static string Agadyrskay {
            get {
                return ResourceManager.GetString("Agadyrskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккаинская РВЛ.
        /// </summary>
        public static string Akkainskay {
            get {
                return ResourceManager.GetString("Akkainskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аккольская РВЛ.
        /// </summary>
        public static string Akkol {
            get {
                return ResourceManager.GetString("Akkol", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аксуская  РВЛ.
        /// </summary>
        public static string Aksuskay {
            get {
                return ResourceManager.GetString("Aksuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аксуская РВЛ.
        /// </summary>
        public static string AksuskayPavl {
            get {
                return ResourceManager.GetString("AksuskayPavl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актау.
        /// </summary>
        public static string Aktau {
            get {
                return ResourceManager.GetString("Aktau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Айтекебийская РВЛ.
        /// </summary>
        public static string Aktekibiisk {
            get {
                return ResourceManager.GetString("Aktekibiisk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актобе.
        /// </summary>
        public static string Aktobe {
            get {
                return ResourceManager.GetString("Aktobe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актогайская  РВЛ.
        /// </summary>
        public static string Aktogaiskay {
            get {
                return ResourceManager.GetString("Aktogaiskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Актогайская РВЛ.
        /// </summary>
        public static string AktogaiskayPav {
            get {
                return ResourceManager.GetString("AktogaiskayPav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акжаикская РВЛ.
        /// </summary>
        public static string Akzhaikskay {
            get {
                return ResourceManager.GetString("Akzhaikskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акжарская ЗВЛ.
        /// </summary>
        public static string Akzharskay {
            get {
                return ResourceManager.GetString("Akzharskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Акжарская РВЛ.
        /// </summary>
        public static string AkzharskaySev {
            get {
                return ResourceManager.GetString("AkzharskaySev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алакольская РВЛ.
        /// </summary>
        public static string Alakolskay {
            get {
                return ResourceManager.GetString("Alakolskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алгинская  РВЛ.
        /// </summary>
        public static string Algynsk {
            get {
                return ResourceManager.GetString("Algynsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алматы.
        /// </summary>
        public static string Almaty {
            get {
                return ResourceManager.GetString("Almaty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Алтынсаринская РВЛ.
        /// </summary>
        public static string Altynsarynskay {
            get {
                return ResourceManager.GetString("Altynsarynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Амангельдинская РВЛ.
        /// </summary>
        public static string Amanfeldinskay {
            get {
                return ResourceManager.GetString("Amanfeldinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аральская РВЛ.
        /// </summary>
        public static string Aralskay {
            get {
                return ResourceManager.GetString("Aralskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аркалыкская РВЛ.
        /// </summary>
        public static string Arkalykskay {
            get {
                return ResourceManager.GetString("Arkalykskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аршалинская РВЛ.
        /// </summary>
        public static string Arshalinsk {
            get {
                return ResourceManager.GetString("Arshalinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Айртауская РВЛ.
        /// </summary>
        public static string Artauskay {
            get {
                return ResourceManager.GetString("Artauskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Арысская РВЛ.
        /// </summary>
        public static string Arysskay {
            get {
                return ResourceManager.GetString("Arysskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Астана.
        /// </summary>
        public static string Astana {
            get {
                return ResourceManager.GetString("Astana", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Астраханская РВЛ.
        /// </summary>
        public static string Astrahansk {
            get {
                return ResourceManager.GetString("Astrahansk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атбасарская РВЛ.
        /// </summary>
        public static string Atbasar {
            get {
                return ResourceManager.GetString("Atbasar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Атырау.
        /// </summary>
        public static string Atyrau {
            get {
                return ResourceManager.GetString("Atyrau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аулиекольская РВЛ.
        /// </summary>
        public static string Aulikolsky {
            get {
                return ResourceManager.GetString("Aulikolsky", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Аягузская РВЛ.
        /// </summary>
        public static string Ayguzkay {
            get {
                return ResourceManager.GetString("Ayguzkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Плохое.
        /// </summary>
        public static string Bad {
            get {
                return ResourceManager.GetString("Bad", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Байдибекская РВЛ.
        /// </summary>
        public static string Baidebekskay {
            get {
                return ResourceManager.GetString("Baidebekskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Байганинская РВЛ.
        /// </summary>
        public static string Baiganinskay {
            get {
                return ResourceManager.GetString("Baiganinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Балхашская   РВЛ.
        /// </summary>
        public static string Balhashskay {
            get {
                return ResourceManager.GetString("Balhashskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Балхашская  ЗВЛ.
        /// </summary>
        public static string BalhashskayZVL {
            get {
                return ResourceManager.GetString("BalhashskayZVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Баршатская ЗВЛ.
        /// </summary>
        public static string Barshatskay {
            get {
                return ResourceManager.GetString("Barshatskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Баршинская ЗВЛ.
        /// </summary>
        public static string Barshinskay {
            get {
                return ResourceManager.GetString("Barshinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Баянаульская РВЛ.
        /// </summary>
        public static string Baynulskay {
            get {
                return ResourceManager.GetString("Baynulskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бейнеуская РВЛ.
        /// </summary>
        public static string Beineuskay {
            get {
                return ResourceManager.GetString("Beineuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бескарагайская РВЛ.
        /// </summary>
        public static string Beskaragayskay {
            get {
                return ResourceManager.GetString("Beskaragayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бокейординская РВЛ.
        /// </summary>
        public static string Bokeiordinskay {
            get {
                return ResourceManager.GetString("Bokeiordinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бородулихинская РВЛ.
        /// </summary>
        public static string Borodulihinskay {
            get {
                return ResourceManager.GetString("Borodulihinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бухар - Жырауская РВЛ.
        /// </summary>
        public static string BuharZhyrau {
            get {
                return ResourceManager.GetString("BuharZhyrau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бурабайская РВЛ.
        /// </summary>
        public static string Burab {
            get {
                return ResourceManager.GetString("Burab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Буландинская РВЛ.
        /// </summary>
        public static string Burlan {
            get {
                return ResourceManager.GetString("Burlan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Бурлинская РВЛ.
        /// </summary>
        public static string Burlinskay {
            get {
                return ResourceManager.GetString("Burlinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чарская ЗВЛ.
        /// </summary>
        public static string Charskay {
            get {
                return ResourceManager.GetString("Charskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чингирлауская РВЛ.
        /// </summary>
        public static string Chingirlauskay {
            get {
                return ResourceManager.GetString("Chingirlauskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Чкаловская ЗВЛ.
        /// </summary>
        public static string Chkalovskay {
            get {
                return ResourceManager.GetString("Chkalovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хромтауская РВЛ.
        /// </summary>
        public static string Chromtauskay {
            get {
                return ResourceManager.GetString("Chromtauskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Денисовская РВЛ.
        /// </summary>
        public static string Denisovskay {
            get {
                return ResourceManager.GetString("Denisovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Егиндыкольская РВЛ.
        /// </summary>
        public static string Egindykolskay {
            get {
                return ResourceManager.GetString("Egindykolskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Екибастузская РВЛ.
        /// </summary>
        public static string Ekibastuzkay {
            get {
                return ResourceManager.GetString("Ekibastuzkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Эмбенская ЗВЛ.
        /// </summary>
        public static string Embinskay {
            get {
                return ResourceManager.GetString("Embinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Енбекшиказахская РВЛ.
        /// </summary>
        public static string Enbebshi {
            get {
                return ResourceManager.GetString("Enbebshi", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Енбекшильдерская РВЛ.
        /// </summary>
        public static string Enbekshyl {
            get {
                return ResourceManager.GetString("Enbekshyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Енбекская ЗВЛ.
        /// </summary>
        public static string Enbekskay {
            get {
                return ResourceManager.GetString("Enbekskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ерейментауская РВЛ.
        /// </summary>
        public static string Erementau {
            get {
                return ResourceManager.GetString("Erementau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есильская РВЛ.
        /// </summary>
        public static string Esil {
            get {
                return ResourceManager.GetString("Esil", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Есильская РВЛ.
        /// </summary>
        public static string Esilskay {
            get {
                return ResourceManager.GetString("Esilskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ескельдинская РВЛ.
        /// </summary>
        public static string Eskeldinskay {
            get {
                return ResourceManager.GetString("Eskeldinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Федоровская РВЛ.
        /// </summary>
        public static string Fedorovskay {
            get {
                return ResourceManager.GetString("Fedorovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хорошее.
        /// </summary>
        public static string Good {
            get {
                return ResourceManager.GetString("Good", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Хобдинская РВЛ.
        /// </summary>
        public static string Hobdinskay {
            get {
                return ResourceManager.GetString("Hobdinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Индерская РВЛ.
        /// </summary>
        public static string Inderskay {
            get {
                return ResourceManager.GetString("Inderskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иргизская РВЛ.
        /// </summary>
        public static string Irgiskay {
            get {
                return ResourceManager.GetString("Irgiskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Иртышская РВЛ.
        /// </summary>
        public static string Irtyshskay {
            get {
                return ResourceManager.GetString("Irtyshskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Исатайская РВЛ.
        /// </summary>
        public static string Isatay {
            get {
                return ResourceManager.GetString("Isatay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Качирская РВЛ.
        /// </summary>
        public static string Kachirskay {
            get {
                return ResourceManager.GetString("Kachirskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Камыстинская РВЛ.
        /// </summary>
        public static string Kamysty {
            get {
                return ResourceManager.GetString("Kamysty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Капальская ЗВЛ.
        /// </summary>
        public static string Kapalskay {
            get {
                return ResourceManager.GetString("Kapalskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Капшагайская ГВЛ.
        /// </summary>
        public static string Kapshagaiskay {
            get {
                return ResourceManager.GetString("Kapshagaiskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карабалыкская РВЛ.
        /// </summary>
        public static string Karabalyk {
            get {
                return ResourceManager.GetString("Karabalyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карабутакская ЗВЛ.
        /// </summary>
        public static string Karabutatskay {
            get {
                return ResourceManager.GetString("Karabutatskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Караганда.
        /// </summary>
        public static string Karag {
            get {
                return ResourceManager.GetString("Karag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каракиянская РВЛ.
        /// </summary>
        public static string Karakiynskay {
            get {
                return ResourceManager.GetString("Karakiynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карасайская РВЛ.
        /// </summary>
        public static string Karasayskay {
            get {
                return ResourceManager.GetString("Karasayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Карасуская РВЛ.
        /// </summary>
        public static string Karasuskay {
            get {
                return ResourceManager.GetString("Karasuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каратальская  РВЛ.
        /// </summary>
        public static string Karatalskay {
            get {
                return ResourceManager.GetString("Karatalskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каражалская ЗВЛ.
        /// </summary>
        public static string Karazhalskay {
            get {
                return ResourceManager.GetString("Karazhalskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каргалинская РВЛ.
        /// </summary>
        public static string Kargalinskay {
            get {
                return ResourceManager.GetString("Kargalinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каркаралинская РВЛ.
        /// </summary>
        public static string Karkaralinskay {
            get {
                return ResourceManager.GetString("Karkaralinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кармакчинская РВЛ.
        /// </summary>
        public static string Karmachkinskay {
            get {
                return ResourceManager.GetString("Karmachkinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Каратобинская РВЛ.
        /// </summary>
        public static string Kartobinskay {
            get {
                return ResourceManager.GetString("Kartobinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Катон-Карагайская РВЛ.
        /// </summary>
        public static string KatonKarag {
            get {
                return ResourceManager.GetString("KatonKarag", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Катон-Карагайская ЗВЛ.
        /// </summary>
        public static string KatonKaragZVL {
            get {
                return ResourceManager.GetString("KatonKaragZVL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Казалинская РВЛ.
        /// </summary>
        public static string Kazalinskay {
            get {
                return ResourceManager.GetString("Kazalinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Казталовская РВЛ.
        /// </summary>
        public static string Kaztalovskay {
            get {
                return ResourceManager.GetString("Kaztalovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Келлеровская ЗВЛ.
        /// </summary>
        public static string Kellerovskay {
            get {
                return ResourceManager.GetString("Kellerovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кентауская РВЛ.
        /// </summary>
        public static string Kentayskay {
            get {
                return ResourceManager.GetString("Kentayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кербулакская    РВЛ.
        /// </summary>
        public static string Kerbulakskay {
            get {
                return ResourceManager.GetString("Kerbulakskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Когалинская  ЗВЛ.
        /// </summary>
        public static string Kogalinskay {
            get {
                return ResourceManager.GetString("Kogalinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кокпектинская РВЛ.
        /// </summary>
        public static string Kokpektinskay {
            get {
                return ResourceManager.GetString("Kokpektinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кордайская РВЛ.
        /// </summary>
        public static string Kordayskay {
            get {
                return ResourceManager.GetString("Kordayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Коргалжинская РВЛ.
        /// </summary>
        public static string Korgazylnsk {
            get {
                return ResourceManager.GetString("Korgazylnsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Костанай.
        /// </summary>
        public static string Kost {
            get {
                return ResourceManager.GetString("Kost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Критичное.
        /// </summary>
        public static string Kritich {
            get {
                return ResourceManager.GetString("Kritich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курчумская РВЛ.
        /// </summary>
        public static string Kurchum {
            get {
                return ResourceManager.GetString("Kurchum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Курмангазинская РВЛ.
        /// </summary>
        public static string Kurmangazy {
            get {
                return ResourceManager.GetString("Kurmangazy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кызылорда.
        /// </summary>
        public static string Kyzyl {
            get {
                return ResourceManager.GetString("Kyzyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кызылкугинская РВЛ.
        /// </summary>
        public static string Kyzylkuginskay {
            get {
                return ResourceManager.GetString("Kyzylkuginskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Кызылжарская РВЛ.
        /// </summary>
        public static string Kyzylzharskay {
            get {
                return ResourceManager.GetString("Kyzylzharskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Казыгуртская РВЛ.
        /// </summary>
        public static string Kyzyrkutskay {
            get {
                return ResourceManager.GetString("Kyzyrkutskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лебяжинская РВЛ.
        /// </summary>
        public static string Lebyzhinskay {
            get {
                return ResourceManager.GetString("Lebyzhinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Лепсинская ЗВЛ.
        /// </summary>
        public static string Lepsindskay {
            get {
                return ResourceManager.GetString("Lepsindskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Махамбетская РВЛ.
        /// </summary>
        public static string Mahambetskay {
            get {
                return ResourceManager.GetString("Mahambetskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Махтааральская РВЛ.
        /// </summary>
        public static string Mahtaaralskay {
            get {
                return ResourceManager.GetString("Mahtaaralskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Маканчинская ЗВЛ.
        /// </summary>
        public static string Makaxhinskay {
            get {
                return ResourceManager.GetString("Makaxhinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мамлютская РВЛ.
        /// </summary>
        public static string Mamlutskay {
            get {
                return ResourceManager.GetString("Mamlutskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мангистауская РВЛ.
        /// </summary>
        public static string Mangystau {
            get {
                return ResourceManager.GetString("Mangystau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на КАРТА.
        /// </summary>
        public static string Map {
            get {
                return ResourceManager.GetString("Map", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мартукская РВЛ.
        /// </summary>
        public static string Martuskay {
            get {
                return ResourceManager.GetString("Martuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Матайская ЗВЛ.
        /// </summary>
        public static string Matayskay {
            get {
                return ResourceManager.GetString("Matayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Майская РВЛ.
        /// </summary>
        public static string Mayskay {
            get {
                return ResourceManager.GetString("Mayskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мендыкаринская РВЛ.
        /// </summary>
        public static string Mendykarinsk {
            get {
                return ResourceManager.GetString("Mendykarinsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Меркенская РВЛ.
        /// </summary>
        public static string Merkenskay {
            get {
                return ResourceManager.GetString("Merkenskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мойнкумская РВЛ.
        /// </summary>
        public static string Moinkumskay {
            get {
                return ResourceManager.GetString("Moinkumskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Молодежная ЗВЛ.
        /// </summary>
        public static string Molodezhnay {
            get {
                return ResourceManager.GetString("Molodezhnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Мугалжарская РВЛ.
        /// </summary>
        public static string Mugalzharskay {
            get {
                return ResourceManager.GetString("Mugalzharskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РВЛ Г. Мусрепова.
        /// </summary>
        public static string Musrepova {
            get {
                return ResourceManager.GetString("Musrepova", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нарынкольская ЗВЛ.
        /// </summary>
        public static string Narynkolskay {
            get {
                return ResourceManager.GetString("Narynkolskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Наурзумская РВЛ.
        /// </summary>
        public static string Naurzumskay {
            get {
                return ResourceManager.GetString("Naurzumskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Нуринская  РВЛ.
        /// </summary>
        public static string Nurinskay {
            get {
                return ResourceManager.GetString("Nurinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Октябрьская  РВЛ.
        /// </summary>
        public static string Oktybyrskay {
            get {
                return ResourceManager.GetString("Oktybyrskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Ордабасинская РВЛ.
        /// </summary>
        public static string Ordabasinskay {
            get {
                return ResourceManager.GetString("Ordabasinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Осакаровская  РВЛ.
        /// </summary>
        public static string Osakarovskay {
            get {
                return ResourceManager.GetString("Osakarovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отличное.
        /// </summary>
        public static string Otlich {
            get {
                return ResourceManager.GetString("Otlich", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Отрарская РВЛ.
        /// </summary>
        public static string Otrarskay {
            get {
                return ResourceManager.GetString("Otrarskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Панфиловская РВЛ.
        /// </summary>
        public static string Panfilov {
            get {
                return ResourceManager.GetString("Panfilov", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Павлодар.
        /// </summary>
        public static string Pavlodar {
            get {
                return ResourceManager.GetString("Pavlodar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Петропавловск.
        /// </summary>
        public static string Petrop {
            get {
                return ResourceManager.GetString("Petrop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Приуральная ЗВЛ.
        /// </summary>
        public static string Priuralnay {
            get {
                return ResourceManager.GetString("Priuralnay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Райымбекская РВЛ.
        /// </summary>
        public static string Raymbekskay {
            get {
                return ResourceManager.GetString("Raymbekskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Самарская ЗВЛ.
        /// </summary>
        public static string Samarskay {
            get {
                return ResourceManager.GetString("Samarskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сандыктауская РВЛ.
        /// </summary>
        public static string Sandyk {
            get {
                return ResourceManager.GetString("Sandyk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Саркандская РВЛ.
        /// </summary>
        public static string Sarkandskay {
            get {
                return ResourceManager.GetString("Sarkandskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сарыагашская РВЛ.
        /// </summary>
        public static string Saryagashskay {
            get {
                return ResourceManager.GetString("Saryagashskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сарыкольская РВЛ.
        /// </summary>
        public static string Sarykolskay {
            get {
                return ResourceManager.GetString("Sarykolskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сарысуская РВЛ.
        /// </summary>
        public static string Sarysuskay {
            get {
                return ResourceManager.GetString("Sarysuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сайрамская РВЛ.
        /// </summary>
        public static string Sayramskay {
            get {
                return ResourceManager.GetString("Sayramskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шалакынская РВЛ.
        /// </summary>
        public static string Shalakynskay {
            get {
                return ResourceManager.GetString("Shalakynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шалкарская РВЛ.
        /// </summary>
        public static string Shalgarskay {
            get {
                return ResourceManager.GetString("Shalgarskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шардаринская РВЛ.
        /// </summary>
        public static string Shardarinskay {
            get {
                return ResourceManager.GetString("Shardarinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шелекская ЗВЛ.
        /// </summary>
        public static string Shelekskay {
            get {
                return ResourceManager.GetString("Shelekskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шемонаихинская РВЛ.
        /// </summary>
        public static string Shemohainskay {
            get {
                return ResourceManager.GetString("Shemohainskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Щербактинская РВЛ.
        /// </summary>
        public static string Sherbaktinskay {
            get {
                return ResourceManager.GetString("Sherbaktinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шетская РВЛ.
        /// </summary>
        public static string Shetskay {
            get {
                return ResourceManager.GetString("Shetskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шиелийская РВЛ.
        /// </summary>
        public static string Shielskay {
            get {
                return ResourceManager.GetString("Shielskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шортандинская РВЛ.
        /// </summary>
        public static string Shortadynsk {
            get {
                return ResourceManager.GetString("Shortadynsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шуская РВЛ.
        /// </summary>
        public static string Shuskay {
            get {
                return ResourceManager.GetString("Shuskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Шымкент.
        /// </summary>
        public static string Shymkent {
            get {
                return ResourceManager.GetString("Shymkent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Среднее.
        /// </summary>
        public static string Srednee {
            get {
                return ResourceManager.GetString("Srednee", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Степногорская ГВЛ.
        /// </summary>
        public static string Stepnog {
            get {
                return ResourceManager.GetString("Stepnog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сузакская РВЛ.
        /// </summary>
        public static string Suzakskay {
            get {
                return ResourceManager.GetString("Suzakskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сырдаринская РВЛ.
        /// </summary>
        public static string Syrdariinskay {
            get {
                return ResourceManager.GetString("Syrdariinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Сырымская РВЛ.
        /// </summary>
        public static string Syrymskay {
            get {
                return ResourceManager.GetString("Syrymskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайпакская ЗВЛ.
        /// </summary>
        public static string Taipakskay {
            get {
                return ResourceManager.GetString("Taipakskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тайыншинская РВЛ.
        /// </summary>
        public static string Taishinskay {
            get {
                return ResourceManager.GetString("Taishinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таласская РВЛ.
        /// </summary>
        public static string Talasskay {
            get {
                return ResourceManager.GetString("Talasskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Талгарская РВЛ.
        /// </summary>
        public static string Talgarskay {
            get {
                return ResourceManager.GetString("Talgarskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарановская РВЛ.
        /// </summary>
        public static string Taranovskay {
            get {
                return ResourceManager.GetString("Taranovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тараз.
        /// </summary>
        public static string Taraz {
            get {
                return ResourceManager.GetString("Taraz", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тарбагатайская РВЛ.
        /// </summary>
        public static string Tarbagait {
            get {
                return ResourceManager.GetString("Tarbagait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Таскалинская РВЛ.
        /// </summary>
        public static string Taskalinskya {
            get {
                return ResourceManager.GetString("Taskalinskya", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Темирская РВЛ.
        /// </summary>
        public static string Temirskay {
            get {
                return ResourceManager.GetString("Temirskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тимирязевская РВЛ.
        /// </summary>
        public static string Temiryzevskay {
            get {
                return ResourceManager.GetString("Temiryzevskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теректинская ЗВЛ.
        /// </summary>
        public static string Terektinskay {
            get {
                return ResourceManager.GetString("Terektinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Теректинская РВЛ.
        /// </summary>
        public static string Terektynskay {
            get {
                return ResourceManager.GetString("Terektynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Токаревская ЗВЛ.
        /// </summary>
        public static string Tokarevskay {
            get {
                return ResourceManager.GetString("Tokarevskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Толебийская РВЛ.
        /// </summary>
        public static string Tolebiskay {
            get {
                return ResourceManager.GetString("Tolebiskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Тюлькубасская РВЛ.
        /// </summary>
        public static string Tulkubakskay {
            get {
                return ResourceManager.GetString("Tulkubakskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Турар-Рыскуловская РВЛ.
        /// </summary>
        public static string TurarRyskul {
            get {
                return ResourceManager.GetString("TurarRyskul", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Туркестанская РВЛ.
        /// </summary>
        public static string Turkestanskay {
            get {
                return ResourceManager.GetString("Turkestanskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уалихановская РВЛ.
        /// </summary>
        public static string Ualihanovkay {
            get {
                return ResourceManager.GetString("Ualihanovkay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уйгурская  РВЛ.
        /// </summary>
        public static string Uigurskay {
            get {
                return ResourceManager.GetString("Uigurskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уилская РВЛ.
        /// </summary>
        public static string Uilskay {
            get {
                return ResourceManager.GetString("Uilskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Улытауская РВЛ.
        /// </summary>
        public static string Ulytau {
            get {
                return ResourceManager.GetString("Ulytau", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уральск.
        /// </summary>
        public static string Uralsk {
            get {
                return ResourceManager.GetString("Uralsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Урджарская РВЛ.
        /// </summary>
        public static string Urdzharskay {
            get {
                return ResourceManager.GetString("Urdzharskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Успенская РВЛ.
        /// </summary>
        public static string Uspenskay {
            get {
                return ResourceManager.GetString("Uspenskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Узункольская РВЛ.
        /// </summary>
        public static string Uzunkolskay {
            get {
                return ResourceManager.GetString("Uzunkolskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на ВЕТЛАБ.
        /// </summary>
        public static string Vetlab {
            get {
                return ResourceManager.GetString("Vetlab", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Уйгентасская ЗВЛ.
        /// </summary>
        public static string Ygentasskay {
            get {
                return ResourceManager.GetString("Ygentasskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Усть - каменогорск.
        /// </summary>
        public static string Yskaman {
            get {
                return ResourceManager.GetString("Yskaman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зайсанская РВЛ.
        /// </summary>
        public static string Zaisan {
            get {
                return ResourceManager.GetString("Zaisan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зеленовская РВЛ.
        /// </summary>
        public static string Zelenovskay {
            get {
                return ResourceManager.GetString("Zelenovskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зерендинская РВЛ.
        /// </summary>
        public static string Zerende {
            get {
                return ResourceManager.GetString("Zerende", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жаксынская РВЛ.
        /// </summary>
        public static string Zhaksynskay {
            get {
                return ResourceManager.GetString("Zhaksynskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жалагашская РВЛ.
        /// </summary>
        public static string Zhalagashskay {
            get {
                return ResourceManager.GetString("Zhalagashskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жалпакталская ЗВЛ.
        /// </summary>
        public static string Zhalpaktaskay {
            get {
                return ResourceManager.GetString("Zhalpaktaskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жамбыльская  РВЛ.
        /// </summary>
        public static string Zhambyl {
            get {
                return ResourceManager.GetString("Zhambyl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жамбылская РВЛ.
        /// </summary>
        public static string Zhambyl2 {
            get {
                return ResourceManager.GetString("Zhambyl2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жамбылская РВЛ.
        /// </summary>
        public static string ZhambylSev {
            get {
                return ResourceManager.GetString("ZhambylSev", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жанакорганская РВЛ.
        /// </summary>
        public static string Zhanakorganskay {
            get {
                return ResourceManager.GetString("Zhanakorganskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жанааркинская  РВЛ.
        /// </summary>
        public static string Zhanarkinskay {
            get {
                return ResourceManager.GetString("Zhanarkinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жангалинская РВЛ.
        /// </summary>
        public static string Zhangalinskay {
            get {
                return ResourceManager.GetString("Zhangalinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жангельдинская РВЛ.
        /// </summary>
        public static string Zhangeldinskay {
            get {
                return ResourceManager.GetString("Zhangeldinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жанибекская РВЛ.
        /// </summary>
        public static string Zhanibekskay {
            get {
                return ResourceManager.GetString("Zhanibekskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жаркаинская РВЛ.
        /// </summary>
        public static string Zharkain {
            get {
                return ResourceManager.GetString("Zharkain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жарминская РВЛ.
        /// </summary>
        public static string Zharminskay {
            get {
                return ResourceManager.GetString("Zharminskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жуалинская РВЛ.
        /// </summary>
        public static string Zhaulynsk {
            get {
                return ResourceManager.GetString("Zhaulynsk", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Железинская РВЛ.
        /// </summary>
        public static string Zhelizinskay {
            get {
                return ResourceManager.GetString("Zhelizinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Житикаринская РВЛ.
        /// </summary>
        public static string Zhetiharinskay {
            get {
                return ResourceManager.GetString("Zhetiharinskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на РВЛ М. Жумабаева.
        /// </summary>
        public static string Zhumabaeva {
            get {
                return ResourceManager.GetString("Zhumabaeva", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Жылойская РВЛ.
        /// </summary>
        public static string Zhyloyskay {
            get {
                return ResourceManager.GetString("Zhyloyskay", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Ищет локализованную строку, похожую на Зыряновская РВЛ.
        /// </summary>
        public static string Zyrynovsk {
            get {
                return ResourceManager.GetString("Zyrynovsk", resourceCulture);
            }
        }
    }
}
